apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftpgo.componentname" (list . "config") }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
data:
  sftpgo.json: |-
    {{- toJson .Values.config | nindent 4 }}
