apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftpgo.fullname" . }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    {{- if .Values.sftpd.enabled }}
    - port: {{ .Values.service.ports.sftp }}
      targetPort: sftp
      protocol: TCP
      name: sftp
    {{- end }}
    {{- if .Values.ftpd.enabled }}
    - port: {{ .Values.service.ports.ftp }}
      targetPort: ftp
      protocol: TCP
      name: ftp
    {{- end }}
    {{- if .Values.webdavd.enabled }}
    - port: {{ .Values.service.ports.webdav }}
      targetPort: webdav
      protocol: TCP
      name: webdav
    {{- end }}
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 10000
      targetPort: telemetry
      protocol: TCP
      name: telemetry
  selector:
    {{- include "sftpgo.selectorLabels" . | nindent 4 }}
